### ISSUE TITLE
[Feature] 설정 화면

### ISSUE THREAD

**Issue by wonst-git** [Eggtart-Mandal-art/Eggtart-Android#38]
## Description
설정 화면

## ToDo
- [ ] 설정 화면 UI
- [ ] 로그아웃 API 연동
- [ ] 회원탈퇴 API 연동

## Etc
기타 사항
